apiVersion: v1
kind: Service
metadata:
  name: {{ include "mm-core.fullname" . }}
  labels: {{- include "mm-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: client
      port: {{ .Values.ports.client }}
      targetPort: client
      protocol: TCP
    - name: metrics
      port: {{ .Values.ports.metrics }}
      targetPort: metrics
      protocol: TCP
  selector: {{- include "mm-core.selectorLabels" . | nindent 4 }}
