apiVersion: v1
kind: Service
metadata:
  name: {{ include "synapse.fullname" . }}
  labels: {{- include "synapse.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.ports.http }}
      targetPort: http
      protocol: TCP
  selector: {{- include "synapse.selectorLabels" . | nindent 4 }}
