# shellcheck shell=bash
# Day-2 lifecycle verbs: init / check / upgrade / restore / uninstall / secrets.
#
# ─────────────────────────────────────────────────────────────────────────────
# THE ROLLBACK CONTRACT — read this before changing anything here.
#
# The database rolls FORWARD ONLY. Migrations are apply-once (mm_schema_migrations);
# there are no down-migrations and there never will be. A new mm-core may add a column,
# backfill it, and drop the old one — running the previous binary against that schema is
# undefined, not "the previous version".
#
# So there is exactly one way back from a bad upgrade: RESTORE FROM BACKUP. Which means a
# backup is not a nice-to-have taken alongside the upgrade — it IS the rollback, and an
# upgrade that proceeds without one has silently removed the operator's only exit. That is
# why `mmctl upgrade` takes the backup FIRST and ABORTS if it fails, rather than warning
# and carrying on.
# ─────────────────────────────────────────────────────────────────────────────

: "${MM_ROOT:=/opt/mm}"

# confirm PROMPT -- 0 if the operator typed exactly "yes".
#
# Destructive verbs gate on this. MM_ASSUME_YES=1 skips it, for automation that has
# already decided — but nothing in this file assumes consent by default.
confirm() {
  local prompt="$1" reply
  [ "${MM_ASSUME_YES:-0}" = "1" ] && return 0
  printf '%s [type "yes" to continue]: ' "$prompt" >&2
  read -r reply
  [ "$reply" = "yes" ]
}

# latest_backup KIND -- newest backup path of KIND (config|pg-app|pg-synapse), or empty.
#
# `ls -t` is safe here despite SC2012: these filenames are generated by backup.sh from a
# UTC timestamp, so they contain no spaces or newlines.
# shellcheck disable=SC2012
latest_backup() {
  local kind="$1"
  ls -1t "$MM_ROOT/backups/${kind}-"*.gz 2>/dev/null | head -1
}

# backup_is_fresh PATH MAX_AGE_SECS -- 0 if PATH exists and is newer than MAX_AGE_SECS.
#
# Guards the case that actually bites: an upgrade "took a backup" by finding a stale one
# from last month. A rollback target that predates a month of messages is not a rollback.
backup_is_fresh() {
  local path="$1" max="${2:-3600}" now age mtime
  [ -n "$path" ] && [ -f "$path" ] || return 1
  now="$(date -u +%s)"
  mtime="$(date -u -r "$path" +%s 2>/dev/null || stat -c %Y "$path" 2>/dev/null)" || return 1
  age=$(( now - mtime ))
  [ "$age" -le "$max" ]
}

# ── init ─────────────────────────────────────────────────────────────────────

# mm_init -- generate secrets and render config WITHOUT starting anything.
#
# For an operator who wants to read the config the installer would run before it runs.
# Idempotent: existing secrets are kept (regenerating them would orphan the database and
# every logged-in session).
mm_init() {
  [ -f "$MM_ROOT/.env" ] || die "no $MM_ROOT/.env — run install.sh first, or write one from .env.example"
  generate_secrets      # keeps existing values; only fills what is missing
  write_secret_files
  render_templates
  log "init OK — config rendered in $MM_ROOT/config. Nothing was started. Review it, then: mmctl start"
}

# ── check ────────────────────────────────────────────────────────────────────

# mm_check -- non-destructive health report. Never changes state.
mm_check() {
  local fail=0
  # shellcheck disable=SC1091
  source "$MM_ROOT/.env"

  # `exited` is NOT healthy — it is a crashed container. The filter used to exclude both
  # `running` AND `exited`, so a service that had died never appeared in "services not
  # running", which is the one question this command exists to answer.
  local unhealthy
  unhealthy="$("${DC[@]}" ps --format '{{.Service}} {{.State}}' 2>/dev/null | grep -vE ' running$' || true)"
  [ -z "$unhealthy" ] || { warn "services NOT running:"; echo "$unhealthy" >&2; fail=1; }

  local disk_gb
  disk_gb=$(( $(df -Pk "$MM_ROOT" 2>/dev/null | awk 'NR==2{print $4}') / 1024 / 1024 ))
  check_min "Disk(GB)" "$disk_gb" 5 || fail=1

  # A backup old enough to be useless is worse than none: it reads as a rollback plan and
  # is not one.
  local cfg; cfg="$(latest_backup config)"
  if [ -z "$cfg" ]; then
    warn "no backup has ever been taken — you have NO way back from a bad upgrade. Run: mmctl backup"
    fail=1
  elif ! backup_is_fresh "$cfg" 604800; then
    warn "newest backup is over a week old ($cfg) — that is your only rollback path"
  fi

  # shellcheck disable=SC1091
  source "$MM_ROOT/.env.secrets"
  MM_TEMP_MODE="$(grep -s '^MM_TEMP_MODE=' "$MM_ROOT/.env" | cut -d= -f2)"; export MM_TEMP_MODE
  self_smoke "$MM_DOMAIN" "${MM_SYNAPSE_ADMIN_TOKEN:-${MM_ADMIN_TOKEN:-}}" || fail=1

  [ "$fail" -eq 0 ] || die "check FAILED (see above)"
  log "check OK"
}

# ── upgrade ──────────────────────────────────────────────────────────────────

# mm_upgrade -- back up, pull, roll, smoke.
#
# The backup is not a courtesy. The DB rolls forward only (see the contract at the top of
# this file), so restore-from-backup is the ONLY way out of a bad upgrade. An upgrade that
# ran without one would have removed the operator's only exit while telling them nothing.
mm_upgrade() {
  log "upgrade: taking a backup first — it is your only rollback (the DB rolls forward only)"
  backup || die "BACKUP FAILED — refusing to upgrade. An upgrade with no backup has no way back."

  # Verify the ROLLBACK, not just that a command exited 0.
  #
  # A config tarball alone is not a rollback: the thing you cannot rebuild is the DATABASE.
  # Check the DB dumps of the same timestamp are present and fresh too — otherwise an
  # upgrade could sail through on a config backup with no database behind it, which is
  # exactly the state the contract exists to prevent.
  local cfg; cfg="$(latest_backup config)"
  backup_is_fresh "$cfg" 3600 || die "no fresh config backup on disk after backup ran — refusing to upgrade"

  local ts; ts="$(basename "$cfg" | sed -E 's/^config-(.*)\.tar\.gz$/\1/')"
  backup_is_fresh "$MM_ROOT/backups/pg-synapse-$ts.sql.gz" 3600 \
    || die "no fresh SYNAPSE database dump for $ts — refusing to upgrade (a config backup is not a rollback)"
  backup_is_fresh "$MM_ROOT/backups/pg-app-$ts.sql.gz" 3600 \
    || die "no fresh APP database dump for $ts — refusing to upgrade (a config backup is not a rollback)"

  log "upgrade: rollback point is $cfg (+ both database dumps for $ts)"

  "${DC[@]}" pull || die "pull failed — nothing was changed"
  "${DC[@]}" up -d --remove-orphans || die "roll failed — restore with: mmctl restore $cfg"

  # shellcheck disable=SC1091
  source "$MM_ROOT/.env"; source "$MM_ROOT/.env.secrets"
  MM_TEMP_MODE="$(grep -s '^MM_TEMP_MODE=' "$MM_ROOT/.env" | cut -d= -f2)"; export MM_TEMP_MODE
  if ! self_smoke "$MM_DOMAIN" "${MM_SYNAPSE_ADMIN_TOKEN:-${MM_ADMIN_TOKEN:-}}"; then
    warn "upgrade rolled but SMOKE FAILED."
    warn "The database has already migrated forward and CANNOT be migrated back."
    warn "To roll back, restore the pre-upgrade state:  mmctl restore $cfg"
    die "upgrade smoke failed"
  fi
  log "upgrade OK (rollback point kept at $cfg)"
}

# ── restore ──────────────────────────────────────────────────────────────────

# restore_one CONTAINER SUPERUSER DB OWNER DUMP LABEL -- replay DUMP into a FRESH DB.
#
# THE FALSE SUCCESS THIS EXISTS TO PREVENT.
#
# This used to be `gunzip -c dump | docker exec -i pg psql -U postgres >/dev/null`, and it
# was not a restore at all:
#
#   * psql WITHOUT `-v ON_ERROR_STOP=1` continues past every error and EXITS 0. The caller
#     saw success.
#   * the dump had no `--clean`, so it was only CREATE/COPY. Replayed into an existing
#     database every statement errored ("relation already exists", "duplicate key") and
#     NOTHING CHANGED.
#   * `>/dev/null` hid stdout; the ERRORs went to stderr and nobody read them.
#   * and `-U postgres` was the wrong role for the Synapse cluster entirely, so its dump
#     never existed in the first place.
#
# Net: an operator rolling back a bad upgrade was told "restore complete" while the database
# stayed byte-for-byte the broken one. It lied at precisely the moment someone depended on it.
#
# Now: drop the database and recreate it EMPTY, then replay into it with ON_ERROR_STOP so
# the first genuine error aborts non-zero. The maintenance connection is `postgres` — a
# database that exists in both clusters and is never the one being dropped.
restore_one() {
  local container="$1" superuser="$2" db="$3" owner="$4" dump="$5" label="$6"

  if [ ! -f "$dump" ]; then
    warn "no $label database dump at $dump — NOT restored, left as-is"
    return 1
  fi

  # Every other session must go, or DROP DATABASE cannot run.
  docker exec "$container" psql -U "$superuser" -d postgres -q -c \
    "SELECT pg_terminate_backend(pid) FROM pg_stat_activity
      WHERE datname = '$db' AND pid <> pg_backend_pid()" >/dev/null 2>&1 || true

  if ! docker exec "$container" psql -U "$superuser" -d postgres -v ON_ERROR_STOP=1 -q \
        -c "DROP DATABASE IF EXISTS \"$db\"" \
        -c "CREATE DATABASE \"$db\" OWNER \"$owner\""; then
    warn "$label: could not recreate database '$db' — NOTHING was restored, the old database is intact"
    return 1
  fi

  if ! ( set -o pipefail
         gunzip -c "$dump" \
           | docker exec -i "$container" psql -U "$superuser" -d "$db" -v ON_ERROR_STOP=1 -q ); then
    warn "$label database restore FAILED mid-replay — '$db' is now INCOMPLETE. Re-run the restore."
    return 1
  fi
  log "restored $label database '$db' from $dump"
}

# mm_restore CONFIG_TARBALL -- restore config + the DB dumps taken alongside it.
#
# This is the documented rollback. It is destructive and it says so.
mm_restore() {
  local cfg="${1:-}"
  [ -n "$cfg" ] || cfg="$(latest_backup config)"
  if [ -z "$cfg" ] || [ ! -f "$cfg" ]; then
    die "no backup to restore (usage: mmctl restore [/path/config-TS.tar.gz])"
  fi

  # The DB dumps are taken in the same run and share the timestamp suffix.
  local ts; ts="$(basename "$cfg" | sed -E 's/^config-(.*)\.tar\.gz$/\1/')"
  local app="$MM_ROOT/backups/pg-app-$ts.sql.gz"
  local syn="$MM_ROOT/backups/pg-synapse-$ts.sql.gz"

  warn "RESTORE will overwrite the current config AND both databases with the state from $ts."
  warn "Everything since then — messages, streams, accounts — is DISCARDED."
  confirm "Restore from $ts?" || die "aborted"

  # Stop every WRITER before touching the databases. `--clean` in the dump issues
  # DROP DATABASE, and Postgres refuses that while any session is connected
  # ("database is being accessed by other users"). Silencing a failed stop and restoring
  # underneath a live writer is how you get a half-restored database.
  if ! "${DC[@]}" stop mm-core synapse mm-switch; then
    die "could not stop the services writing to the databases — refusing to restore"
  fi

  tar xzf "$cfg" -C "$MM_ROOT" || die "config restore FAILED (tar) — nothing else was touched"
  log "restored config from $cfg"

  local rc=0
  restore_one "$MM_PG_SYNAPSE_CONTAINER" "$MM_PG_SYNAPSE_SUPERUSER" \
              "$MM_PG_SYNAPSE_DB" "$MM_PG_SYNAPSE_OWNER" "$syn" "synapse" || rc=1
  restore_one "$MM_PG_APP_CONTAINER" "$MM_PG_APP_SUPERUSER" \
              "$MM_PG_APP_DB" "$MM_PG_APP_OWNER" "$app" "app" || rc=1

  "${DC[@]}" up -d

  if [ "$rc" -ne 0 ]; then
    die "RESTORE FAILED — the database is NOT the one you asked for. Do not treat this as a rollback."
  fi
  log "restore complete — verify with: mmctl check"
}

# ── uninstall ────────────────────────────────────────────────────────────────

# mm_uninstall [--purge] -- stop the stack. --purge also destroys the data volumes.
#
# Without --purge the volumes survive, so `mmctl start` brings the server back exactly as
# it was. --purge is irreversible and is gated behind an explicit confirmation, because
# nothing about "uninstall" tells an operator that their messages are about to be deleted.
mm_uninstall() {
  local purge=0
  [ "${1:-}" = "--purge" ] && purge=1

  if [ "$purge" -eq 1 ]; then
    warn "--purge DESTROYS the data volumes: every message, account, stream and recording."
    warn "This is NOT recoverable unless you have a backup."
    local cfg; cfg="$(latest_backup config)"
    if [ -n "$cfg" ]; then
      warn "newest backup: $cfg"
    else
      warn "you have NO backup. This is unrecoverable."
    fi
    confirm "Permanently destroy all data?" || die "aborted"
    "${DC[@]}" down -v --remove-orphans
    log "stack removed and volumes destroyed. Config remains in $MM_ROOT (delete it yourself)."
  else
    "${DC[@]}" down --remove-orphans
    log "stack stopped; DATA VOLUMES KEPT. Bring it back with: mmctl start   (destroy data: mmctl uninstall --purge)"
  fi
}

# ── secrets ──────────────────────────────────────────────────────────────────

# mm_secrets -- report which secrets are present. NEVER prints a value.
mm_secrets() {
  [ -f "$MM_ROOT/.env.secrets" ] || die "no $MM_ROOT/.env.secrets"
  local name
  # Values are deliberately never echoed: this runs on a terminal an operator may be
  # screen-sharing, and it is the kind of convenience that leaks an admin token.
  while IFS='=' read -r name _; do
    case "$name" in ''|\#*) continue ;; esac
    printf '%-34s present\n' "$name"
  done < "$MM_ROOT/.env.secrets"
  log "rotate one with: mmctl rotate <NAME>"
}
