# shellcheck shell=bash
# Day-2 lifecycle verbs: init / check / upgrade / restore / uninstall / secrets.
#
# ─────────────────────────────────────────────────────────────────────────────
# THE ROLLBACK CONTRACT — read this before changing anything here.
#
# The database rolls FORWARD ONLY. Migrations are apply-once (mm_schema_migrations);
# there are no down-migrations and there never will be. A new mm-core may add a column,
# backfill it, and drop the old one — running the previous binary against that schema is
# undefined, not "the previous version".
#
# So there is exactly one way back from a bad upgrade: RESTORE FROM BACKUP. Which means a
# backup is not a nice-to-have taken alongside the upgrade — it IS the rollback, and an
# upgrade that proceeds without one has silently removed the operator's only exit. That is
# why `mmctl upgrade` takes the backup FIRST and ABORTS if it fails, rather than warning
# and carrying on.
# ─────────────────────────────────────────────────────────────────────────────

: "${MM_ROOT:=/opt/mm}"

# confirm PROMPT -- 0 if the operator typed exactly "yes".
#
# Destructive verbs gate on this. MM_ASSUME_YES=1 skips it, for automation that has
# already decided — but nothing in this file assumes consent by default.
confirm() {
  local prompt="$1" reply
  [ "${MM_ASSUME_YES:-0}" = "1" ] && return 0
  printf '%s [type "yes" to continue]: ' "$prompt" >&2
  read -r reply
  [ "$reply" = "yes" ]
}

# latest_backup KIND -- newest backup path of KIND (config|pg-app|pg-synapse), or empty.
#
# `ls -t` is safe here despite SC2012: these filenames are generated by backup.sh from a
# UTC timestamp, so they contain no spaces or newlines.
# shellcheck disable=SC2012
latest_backup() {
  local kind="$1"
  ls -1t "$MM_ROOT/backups/${kind}-"*.gz 2>/dev/null | head -1
}

# backup_is_fresh PATH MAX_AGE_SECS -- 0 if PATH exists and is newer than MAX_AGE_SECS.
#
# Guards the case that actually bites: an upgrade "took a backup" by finding a stale one
# from last month. A rollback target that predates a month of messages is not a rollback.
backup_is_fresh() {
  local path="$1" max="${2:-3600}" now age mtime
  [ -n "$path" ] && [ -f "$path" ] || return 1
  now="$(date -u +%s)"
  mtime="$(date -u -r "$path" +%s 2>/dev/null || stat -c %Y "$path" 2>/dev/null)" || return 1
  age=$(( now - mtime ))
  [ "$age" -le "$max" ]
}

# ── init ─────────────────────────────────────────────────────────────────────

# mm_init -- generate secrets and render config WITHOUT starting anything.
#
# For an operator who wants to read the config the installer would run before it runs.
# Idempotent: existing secrets are kept (regenerating them would orphan the database and
# every logged-in session).
mm_init() {
  [ -f "$MM_ROOT/.env" ] || die "no $MM_ROOT/.env — run install.sh first, or write one from .env.example"
  generate_secrets      # keeps existing values; only fills what is missing
  write_secret_files
  render_templates
  log "init OK — config rendered in $MM_ROOT/config. Nothing was started. Review it, then: mmctl start"
}

# ── check ────────────────────────────────────────────────────────────────────

# mm_check -- non-destructive health report. Never changes state.
mm_check() {
  local fail=0
  # shellcheck disable=SC1091
  source "$MM_ROOT/.env"

  local unhealthy
  unhealthy="$("${DC[@]}" ps --format '{{.Service}} {{.State}}' 2>/dev/null | grep -vE ' (running|exited)$' || true)"
  [ -z "$unhealthy" ] || { warn "services not running:"; echo "$unhealthy" >&2; fail=1; }

  local disk_gb
  disk_gb=$(( $(df -Pk "$MM_ROOT" 2>/dev/null | awk 'NR==2{print $4}') / 1024 / 1024 ))
  check_min "Disk(GB)" "$disk_gb" 5 || fail=1

  # A backup old enough to be useless is worse than none: it reads as a rollback plan and
  # is not one.
  local cfg; cfg="$(latest_backup config)"
  if [ -z "$cfg" ]; then
    warn "no backup has ever been taken — you have NO way back from a bad upgrade. Run: mmctl backup"
    fail=1
  elif ! backup_is_fresh "$cfg" 604800; then
    warn "newest backup is over a week old ($cfg) — that is your only rollback path"
  fi

  # shellcheck disable=SC1091
  source "$MM_ROOT/.env.secrets"
  self_smoke "$MM_DOMAIN" "${MM_SYNAPSE_ADMIN_TOKEN:-${MM_ADMIN_TOKEN:-}}" || fail=1

  [ "$fail" -eq 0 ] || die "check FAILED (see above)"
  log "check OK"
}

# ── upgrade ──────────────────────────────────────────────────────────────────

# mm_upgrade -- back up, pull, roll, smoke.
#
# The backup is not a courtesy. The DB rolls forward only (see the contract at the top of
# this file), so restore-from-backup is the ONLY way out of a bad upgrade. An upgrade that
# ran without one would have removed the operator's only exit while telling them nothing.
mm_upgrade() {
  log "upgrade: taking a backup first — it is your only rollback (the DB rolls forward only)"
  backup || die "BACKUP FAILED — refusing to upgrade. An upgrade with no backup has no way back."

  local cfg; cfg="$(latest_backup config)"
  backup_is_fresh "$cfg" 3600 || die "no fresh backup on disk after backup ran — refusing to upgrade"
  log "upgrade: rollback point is $cfg"

  "${DC[@]}" pull || die "pull failed — nothing was changed"
  "${DC[@]}" up -d --remove-orphans || die "roll failed — restore with: mmctl restore $cfg"

  # shellcheck disable=SC1091
  source "$MM_ROOT/.env"; source "$MM_ROOT/.env.secrets"
  if ! self_smoke "$MM_DOMAIN" "${MM_SYNAPSE_ADMIN_TOKEN:-${MM_ADMIN_TOKEN:-}}"; then
    warn "upgrade rolled but SMOKE FAILED."
    warn "The database has already migrated forward and CANNOT be migrated back."
    warn "To roll back, restore the pre-upgrade state:  mmctl restore $cfg"
    die "upgrade smoke failed"
  fi
  log "upgrade OK (rollback point kept at $cfg)"
}

# ── restore ──────────────────────────────────────────────────────────────────

# mm_restore CONFIG_TARBALL -- restore config + the DB dumps taken alongside it.
#
# This is the documented rollback. It is destructive and it says so.
mm_restore() {
  local cfg="${1:-}"
  [ -n "$cfg" ] || cfg="$(latest_backup config)"
  if [ -z "$cfg" ] || [ ! -f "$cfg" ]; then
    die "no backup to restore (usage: mmctl restore [/path/config-TS.tar.gz])"
  fi

  # The DB dumps are taken in the same run and share the timestamp suffix.
  local ts; ts="$(basename "$cfg" | sed -E 's/^config-(.*)\.tar\.gz$/\1/')"
  local app="$MM_ROOT/backups/pg-app-$ts.sql.gz"
  local syn="$MM_ROOT/backups/pg-synapse-$ts.sql.gz"

  warn "RESTORE will overwrite the current config AND both databases with the state from $ts."
  warn "Everything since then — messages, streams, accounts — is DISCARDED."
  confirm "Restore from $ts?" || die "aborted"

  "${DC[@]}" stop mm-core synapse >/dev/null 2>&1 || true

  tar xzf "$cfg" -C "$MM_ROOT"
  log "restored config from $cfg"

  # if/then/else, not `A && B || C`: in that idiom C also runs when A succeeds but B fails,
  # which here would report a restore as FAILED after it worked. This is the data-recovery
  # path; it does not get to be cute.
  local restored_db=0
  if [ -f "$syn" ]; then
    if gunzip -c "$syn" | docker exec -i matrixmedia-postgres-1 psql -U postgres >/dev/null; then
      log "restored synapse DB from $syn"
      restored_db=1
    else
      warn "synapse DB restore FAILED — the config is back but the database is NOT"
    fi
  else
    warn "no synapse DB dump for $ts — config restored, database left as-is"
  fi
  if [ -f "$app" ]; then
    if gunzip -c "$app" | docker exec -i matrixmedia-mm-postgres-1 psql -U postgres >/dev/null; then
      log "restored app DB from $app"
      restored_db=1
    else
      warn "app DB restore FAILED — the config is back but the database is NOT"
    fi
  else
    warn "no app DB dump for $ts — config restored, database left as-is"
  fi

  "${DC[@]}" up -d
  [ "$restored_db" -eq 1 ] || warn "NO database was restored. If you were rolling back an upgrade, you are still on the NEW schema."
  log "restore complete — verify with: mmctl check"
}

# ── uninstall ────────────────────────────────────────────────────────────────

# mm_uninstall [--purge] -- stop the stack. --purge also destroys the data volumes.
#
# Without --purge the volumes survive, so `mmctl start` brings the server back exactly as
# it was. --purge is irreversible and is gated behind an explicit confirmation, because
# nothing about "uninstall" tells an operator that their messages are about to be deleted.
mm_uninstall() {
  local purge=0
  [ "${1:-}" = "--purge" ] && purge=1

  if [ "$purge" -eq 1 ]; then
    warn "--purge DESTROYS the data volumes: every message, account, stream and recording."
    warn "This is NOT recoverable unless you have a backup."
    local cfg; cfg="$(latest_backup config)"
    if [ -n "$cfg" ]; then
      warn "newest backup: $cfg"
    else
      warn "you have NO backup. This is unrecoverable."
    fi
    confirm "Permanently destroy all data?" || die "aborted"
    "${DC[@]}" down -v --remove-orphans
    log "stack removed and volumes destroyed. Config remains in $MM_ROOT (delete it yourself)."
  else
    "${DC[@]}" down --remove-orphans
    log "stack stopped; DATA VOLUMES KEPT. Bring it back with: mmctl start   (destroy data: mmctl uninstall --purge)"
  fi
}

# ── secrets ──────────────────────────────────────────────────────────────────

# mm_secrets -- report which secrets are present. NEVER prints a value.
mm_secrets() {
  [ -f "$MM_ROOT/.env.secrets" ] || die "no $MM_ROOT/.env.secrets"
  local name
  # Values are deliberately never echoed: this runs on a terminal an operator may be
  # screen-sharing, and it is the kind of convenience that leaks an admin token.
  while IFS='=' read -r name _; do
    case "$name" in ''|\#*) continue ;; esac
    printf '%-34s present\n' "$name"
  done < "$MM_ROOT/.env.secrets"
  log "rotate one with: mmctl rotate <NAME>"
}
