[package]
name = "mm-sfu"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mm-core = { workspace = true }

thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
reqwest = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
tokio = { workspace = true }
jsonwebtoken = { workspace = true }
livekit-api = { workspace = true }
livekit-protocol = { workspace = true }
sha2 = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true }
