[package]
name = "mm-api"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mm-core = { workspace = true }
mm-db = { workspace = true }
mm-sfu = { workspace = true }
mm-matrix = { workspace = true }
mm-payment = { workspace = true }
mm-recommendations = { workspace = true }
mm-ads = { workspace = true }

axum = { workspace = true }
http = "1"
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
governor = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
prometheus = { workspace = true }
sqlx = { workspace = true }
async-stripe = { workspace = true }
reqwest = { workspace = true }
urlencoding = "2"
