apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrixmedia.fullname" . }}
  labels:
    {{- include "matrixmedia.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.clientPort }}
      targetPort: client
      protocol: TCP
      name: client
  selector:
    {{- include "matrixmedia.selectorLabels" . | nindent 4 }}
