apiVersion: v1
kind: Service
metadata:
  name: {{ include "matrixmedia.fullname" . }}-admin
  labels:
    {{- include "matrixmedia.labels" . | nindent 4 }}
    app.kubernetes.io/component: admin
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.adminPort }}
      targetPort: admin
      protocol: TCP
      name: admin
  selector:
    {{- include "matrixmedia.selectorLabels" . | nindent 4 }}
