apiVersion: v1
kind: Service
metadata:
  name: {{ include "coturn.fullname" . }}
  labels: {{- include "coturn.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- with .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ . | quote }}
  {{- end }}
  ports:
    - name: stun-turn-udp
      port: {{ .Values.ports.stunTurn }}
      targetPort: stun-turn-udp
      protocol: UDP
    - name: stun-turn-tcp
      port: {{ .Values.ports.stunTurn }}
      targetPort: stun-turn-tcp
      protocol: TCP
    - name: tls
      port: {{ .Values.ports.tls }}
      targetPort: tls
      protocol: TCP
{{- range $port := untilStep (int .Values.ports.relayUdpStart) (int (add 1 (int .Values.ports.relayUdpEnd))) 1 }}
    - name: relay-{{ $port }}
      port: {{ $port }}
      targetPort: {{ $port }}
      protocol: UDP
{{- end }}
  selector: {{- include "coturn.selectorLabels" . | nindent 4 }}
